### ISSUE TITLE
13.4.0 Batch downloader

### ISSUE THREAD

**Issue by hmaegaard** [Piwigo/Piwigo-BatchDownloader#43] opened 2022-12-22 11:02 UTC
PHP version 8.0 or 8.1.
The batch downloader gives following warning on the client side:

<b>Warning</b>:  Undefined array key "BATCH_DWN_SIZE" in <b>/File path/public_html/galleri/_data/templates_c/i5hokb^7ae144d405a9dee0b00857a409a6d9fe579e86a3_0.file.download_button.tpl.php</b> on line <b>25</b><br />
  | <br />
  | <b>Warning</b>:  Attempt to read property "value" on null in <b>/Filepath/public_html/galleri/_data/templates_c/i5hokb^7ae144d405a9dee0b00857a409a6d9fe579e86a3_0.file.download_button.tpl.php</b> on line <b>25</b><br />

**Comment by 2otherjobs** [comment] 2023-01-09 21:44
I have the same issue using php version 8.0.  Behavior:  The batch_downloader can send an album's photos to a collection as intended.  However, buttons on the collection page do not function, so downloading cannot take place.

/usr/local/www/piwigo/_data/templates_c/dreuz4^3be880561dc5756f5edca4b93399fdcf36c3740b_0.file.download_button.tpl.php on line 25

Warning: Attempt to read property "value" on null in /usr/local/www/piwigo/_data/templates_c/dreuz4^3be880561dc5756f5edca4b93399fdcf36c3740b_0.file.download_button.tpl.php on line 25
" id="batchDownloadLink" title="Download all pictures of this selection" class="pwg-state-default pwg-button" rel="nofollow">

**Comment by Spydlack** [comment] 2023-02-02 08:56
I have the same problem with php 8.1

**Comment by transitriderproductions** [comment] 2023-04-09 22:43
This will work if you set your PHP to 7.4, which I did and it worked

**Comment by 2otherjobs** [comment] 2023-04-10 17:51
Support for and Security updates for php74 ended December 2022.   It really is unfortunate if that is the only version that works. Sent from my iPhoneOn Apr 9, 2023, at 5:43 PM, TransitRider Productions ***@***.***> wrote:﻿
This will work if you set your PHP to 7.4, which I did and it worked

**Comment by plegall** [comment] 2023-05-10 08:52
fixes released in version 13.a

**Closed by plegall** 2023-05-10 08:52 UTC

**Comment by 2otherjobs** [comment] 2023-05-10 19:58
Thanks.  Sent from my iPhoneOn May 10, 2023, at 3:52 AM, Pierrick Le Gall ***@***.***> wrote:﻿
Closed #43 as completed.
